import {describe,it,expect,vi,afterEach} from 'vitest';
import {Coordinator} from '../src/main/coordinator';
import {defaults,selectProfile} from '../src/shared/config';
const create=()=>{const capture={start:vi.fn(async()=>{}),stop:vi.fn()};const c=new Coordinator(capture,()=>{});return {c,capture};};
afterEach(()=>vi.useRealTimers());
describe('session ownership',()=>{
 it('requires credentials for live streams',async()=>{const {c,capture}=create();await expect(c.start()).rejects.toThrow();expect(capture.start).not.toHaveBeenCalled();});
 it('rapid Start is idempotent; stop releases capture and rejects late formats',async()=>{const {c,capture}=create();await Promise.all([c.start(false,true),c.start(false,true)]);expect(capture.start).toHaveBeenCalledTimes(1);const epoch=c.state.transcript.epoch;await c.stop();c.format(epoch,{sampleRate:48000,channels:2});expect(c.state.audio).toBeNull();expect(capture.stop).toHaveBeenCalled();c.dispose();});
 it('local test gets real sample statistics and never opens a socket',async()=>{const {c}=create();await c.start(false,true);const epoch=c.state.transcript.epoch;c.format(epoch,{sampleRate:48000,channels:2});c.packet(epoch,0,new Int16Array([1000,-1000,1000,-1000]).buffer);expect(c.state.packets).toBe(1);expect(c.state.meter).toBeGreaterThan(0);expect(c.state.networkHealth).toBe('Not connected');c.dispose();});
 it('packet discontinuity stops instead of silently dropping',async()=>{const {c}=create();await c.start(false,true);const epoch=c.state.transcript.epoch;c.format(epoch,{sampleRate:48000,channels:2});c.packet(epoch,5,new Int16Array([0,0]).buffer);expect(c.state.status).toBe('error');c.dispose();});
 it('profile changes stage; display-only changes do not restart',async()=>{vi.useFakeTimers();const {c,capture}=create();await c.start(true);const updated={...c.state.preferences,processing:selectProfile(defaults.processing,'Speed')};await c.preferences(updated,'pause');expect(c.state.effective?.profile).toBe('Balanced');expect(c.state.pending?.config.profile).toBe('Speed');await c.preferences({...updated,drafts:false},'pause');expect(c.state.effective?.profile).toBe('Balanced');expect(capture.start).not.toHaveBeenCalled();await c.stop('paused');await c.start(true);expect(c.state.effective?.profile).toBe('Speed');expect(c.state.preferences.drafts).toBe(false);c.dispose();});
 it('next-session changes do not apply on resume',async()=>{vi.useFakeTimers();const {c}=create();await c.start(true);await c.preferences({...c.state.preferences,processing:selectProfile(defaults.processing,'Accuracy-first')},'next');await c.stop('paused');await c.start(true);expect(c.state.effective?.profile).toBe('Balanced');await c.stop();await c.start(true);expect(c.state.effective?.profile).toBe('Accuracy-first');c.dispose();});
 it('clear prevents late demo tokens restoring transcript',async()=>{vi.useFakeTimers();const {c}=create();await c.start(true);vi.advanceTimersByTime(1200);expect(c.state.transcript.groups.length).toBeGreaterThan(0);await c.clear();vi.advanceTimersByTime(5000);expect(c.state.transcript.groups).toHaveLength(0);c.dispose();});
});
