import {EventEmitter} from 'node:events';
import WebSocket from 'ws';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {Coordinator} from '../src/main/coordinator';
import {defaults,selectProfile} from '../src/shared/config';
class Socket extends EventEmitter{readyState=0;bufferedAmount=0;sent:(string|Buffer)[]=[];send(data:string|Buffer){this.sent.push(data);}terminate(){this.readyState=3;}open(){this.readyState=1;this.emit('open');}close(){this.readyState=3;this.emit('close');}message(data:unknown){this.emit('message',Buffer.from(JSON.stringify(data)));}}
function setup(){const sockets:Socket[]=[];const capture={start:vi.fn(async()=>{}),stop:vi.fn()};const c=new Coordinator(capture,()=>{},structuredClone(defaults),()=>{const s=new Socket();sockets.push(s);return s as unknown as WebSocket;});c.key='synthetic-test-key';return {c,capture,sockets};}
afterEach(()=>vi.useRealTimers());
describe('wire lifecycle with fake transport (no paid calls)',()=>{
 it('sends configuration before queued PCM and caps backpressure',async()=>{const {c,sockets}=setup();await c.start();const epoch=c.state.transcript.epoch;c.format(epoch,{sampleRate:48000,channels:2});c.packet(epoch,0,new Int16Array([1,2]).buffer);sockets[0].open();expect(JSON.parse(sockets[0].sent[0] as string)).toMatchObject({api_key:'synthetic-test-key',model:'stt-rt-v5',max_endpoint_delay_ms:2000});expect(Buffer.isBuffer(sockets[0].sent[1])).toBe(true);sockets[0].bufferedAmount=384000;c.packet(epoch,1,new Int16Array([3,4]).buffer);expect(c.state.status).toBe('error');c.dispose();});
 it('stop releases capture first, accepts bounded final tokens and rejects later ones',async()=>{const {c,capture,sockets}=setup();await c.start();const epoch=c.state.transcript.epoch;c.format(epoch,{sampleRate:48000,channels:2});sockets[0].open();const stopping=c.stop();expect(capture.stop).toHaveBeenCalled();expect(c.state.status).toBe('stopping');sockets[0].message({tokens:[{text:'Final text',is_final:true}]});sockets[0].message({finished:true});await stopping;expect(c.state.transcript.groups[0].source).toBe('Final text');sockets[0].message({tokens:[{text:'Late text',is_final:true}]});expect(c.state.transcript.groups[0].source).toBe('Final text');c.dispose();});
 it('stop while a live profile reconnect drains cancels the restart',async()=>{const {c,sockets}=setup();await c.start();c.format(c.state.transcript.epoch,{sampleRate:48000,channels:2});sockets[0].open();const applying=c.preferences({...c.state.preferences,processing:selectProfile(defaults.processing,'Speed')},'now');const stop=c.stop();sockets[0].message({finished:true});await Promise.all([stop,applying]);expect(c.state.status).toBe('stopped');expect(sockets).toHaveLength(1);c.dispose();});
 it('rejects invalid config without changing active/saved state',async()=>{const {c}=setup();const old=c.state.preferences;await expect(c.preferences({...old,processing:{...old.processing,endpoint:{...old.processing.endpoint,delay:NaN}}},'now')).rejects.toThrow();expect(c.state.preferences).toBe(old);c.dispose();});
 it('manual finalization is explicit and not confused with hold',async()=>{const {c,sockets}=setup();await c.start();c.format(c.state.transcript.epoch,{sampleRate:48000,channels:2});sockets[0].open();c.state.hold=structuredClone(c.state.transcript);expect(sockets[0].sent).toHaveLength(1);c.finalize();expect(sockets[0].sent[1]).toBe('{"type":"finalize"}');c.dispose();});
 it('stop has a bounded drain even when provider never finishes',async()=>{vi.useFakeTimers();const {c,sockets}=setup();await c.start();c.format(c.state.transcript.epoch,{sampleRate:48000,channels:2});sockets[0].open();const stopped=c.stop();vi.advanceTimersByTime(3001);await stopped;expect(c.state.status).toBe('stopped');expect(sockets[0].readyState).toBe(3);c.dispose();});
});
