import {desktopScreenshot} from './desktop-screenshot';
import {_electron as electron,test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
test('meeting save/restart/review/delete, supplied glossary and native floating controls',async()=>{
 const args=['.','--test-isolated',`--test-profile=meetings-${Date.now()}`,'--visual-fixture'];
 const env=Object.fromEntries(Object.entries(process.env).filter(([k,v])=>k!=='ELECTRON_RUN_AS_NODE'&&v!==undefined)) as Record<string,string>;
 let app=await electron.launch({args,env});const dir='test-results/meetings';await mkdir(dir,{recursive:true});
 try{const page=await app.firstWindow();const view=await app.browserWindow(page);await view.evaluate(w=>w.setSize(1280,800));page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Your meetings',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.intera.snapshot().then(s=>s.storageLoading))).toBe(false);const s=await page.evaluate(()=>window.intera.snapshot());if(s.secureStorage){await page.getByLabel('Meeting title').fill('Synthetic insurance practice');await page.getByRole('button',{name:'Stop & save meeting',exact:true}).click();await expect(page.getByText('Meeting saved on this device.',{exact:true})).toBeVisible();await expect(page.getByText('Synthetic insurance practice',{exact:true})).toBeVisible();}
  await desktopScreenshot(app,page,{path:`${dir}/library.png`});
  await page.getByRole('button',{name:'New meeting',exact:true}).click();expect((await page.evaluate(()=>window.intera.snapshot())).transcript.groups).toHaveLength(0);
 }finally{await app.close();}
 app=await electron.launch({args:args.filter(a=>a!=='--visual-fixture'),env});
 try{const page=await app.firstWindow();const view=await app.browserWindow(page);await view.evaluate(w=>w.setSize(1280,800));page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Your meetings',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.intera.snapshot().then(s=>s.storageLoading))).toBe(false);const s=await page.evaluate(()=>window.intera.snapshot());if(s.secureStorage){await expect(page.getByText('Synthetic insurance practice',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Open',exact:true}).click();expect((await page.evaluate(()=>window.intera.snapshot())).meetingReview).toBe(true);expect((await page.evaluate(()=>window.intera.command({type:'start'}))).ok).toBe(false);await page.getByRole('button',{name:'Delete',exact:true}).click();expect((await page.evaluate(()=>window.intera.snapshot())).meetings).toHaveLength(0);}
  await page.getByRole('button',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:'Browse supplied medical & insurance preset'}).click();await page.getByLabel('Search supplied glossary').fill('deductible');await expect(page.locator('.glossary-entry').first()).toBeVisible();await page.locator('.glossary-entry input').first().check();await page.getByRole('button',{name:'Load selected terms',exact:true}).click();await expect(page.getByLabel('Directional translation mappings (source = target)')).not.toHaveValue('');await desktopScreenshot(app,page,{path:`${dir}/supplied-glossary.png`});
  await page.getByRole('button',{name:'Window',exact:true}).click();const next=app.waitForEvent('window');await page.getByRole('button',{name:'Open floating reader'}).click();const compact=await next;await compact.waitForLoadState();const native=await app.browserWindow(compact);expect(await native.evaluate(w=>w.isAlwaysOnTop())).toBe(true);
  await page.getByLabel('Keep the compact reader above other windows').uncheck();await expect.poll(()=>native.evaluate(w=>w.isAlwaysOnTop())).toBe(false);
  await page.getByLabel('Request exclusion from screen capture').check();await expect.poll(()=>native.evaluate(w=>w.isContentProtected())).toBe(true);await page.getByLabel('Request exclusion from screen capture').uncheck();await expect.poll(()=>native.evaluate(w=>w.isContentProtected())).toBe(false);
  await desktopScreenshot(app,page,{path:`${dir}/floating-sharing.png`});await page.getByRole('button',{name:'Updates',exact:true}).click();await expect(page.getByRole('button',{name:'Check for updates',exact:true})).toBeDisabled();await desktopScreenshot(app,page,{path:`${dir}/updates-blocked.png`});
  await page.getByRole('button',{name:'Window',exact:true}).click();await page.evaluate(async()=>{const s=await window.intera.snapshot();await window.intera.command({type:'preferences',preferences:{...s.preferences,theme:'dark'},timing:'next'});});await desktopScreenshot(app,page,{path:`${dir}/floating-dark.png`});
  await view.evaluate(w=>{w.setSize(680,700);w.webContents.setZoomFactor(1.5);});await desktopScreenshot(app,page,{path:`${dir}/floating-narrow-150.png`});
 }finally{await app.close();}
});
