import React,{useEffect,useState} from 'react';
import type {State,Command} from '../shared/protocol';
import {gazeDefaults,type GazeSettings} from '../shared/eye-contact';
export function EyeContactPanel({s,send}:{s:State;send:(command:Command)=>Promise<{ok:boolean;message?:string}>}){
 const [settings,setSettings]=useState<GazeSettings>({...gazeDefaults}),[frame,setFrame]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const remove=window.intera.gazeFrames(setFrame);void send({type:'gaze-check'});return()=>{remove();void send({type:'gaze-stop'});};},[]);
 const active=s.eyeContact?.status==='preview'||s.eyeContact?.status==='starting';
 async function perform(command:Command){const result=await send(command);setMessage(result.ok?'':result.message??'Camera action failed.');}
 function change(next:GazeSettings){setSettings(next);if(s.eyeContact?.status==='preview')void perform({type:'gaze-configure',settings:next});}
 return <section aria-label="Integrated eye contact"><h3>Eye contact</h3><p>Local camera preview and calibration inside Intera. Development feature for macOS 14 or later.</p><p role="status">{s.eyeContact?.message??'Checking availability…'}</p><div style={{background:'#171D26',minHeight:220,borderRadius:12,display:'grid',placeItems:'center',overflow:'hidden'}}>{frame?<img alt="Live local camera preview — not a Zoom output" src={'data:image/jpeg;base64,'+frame} style={{width:'100%',maxWidth:640}}/>:<p style={{color:'#EDF1F5'}}>Camera off</p>}</div><p className="hint">Zoom output is not implemented yet. This preview does not create a camera in Zoom. No camera recordings or frame uploads.</p><label>Camera index <input type="number" min="0" max="8" value={settings.camera} disabled={active} onChange={e=>change({...settings,camera:Number(e.target.value)})}/></label><label><input type="checkbox" checked={settings.enabled} onChange={e=>change({...settings,enabled:e.target.checked})}/>Enable correction when models are loaded</label>{(['offsetX','offsetY','offsetZ','focalLength'] as const).map(key=><label key={key}>{({offsetX:'Camera horizontal offset (cm)',offsetY:'Camera vertical offset (cm)',offsetZ:'Camera depth offset (cm)',focalLength:'Focal length (px)'})[key]}<input type="number" step={key==='focalLength'?10:0.5} min={key==='focalLength'?300:key==='offsetY'?-40:key==='offsetX'?-30:-20} max={key==='focalLength'?1500:key==='offsetY'?40:key==='offsetX'?30:20} value={settings[key]} onChange={e=>change({...settings,[key]:Number(e.target.value)})}/></label>)}<div className="actions"><button disabled={active||!s.eyeContact?.installed} onClick={()=>void perform({type:'gaze-start',settings})}>Start local camera preview</button><button disabled={!active} onClick={()=>void perform({type:'gaze-stop'})}>Stop camera</button><button onClick={()=>change({...gazeDefaults,camera:settings.camera})}>Reset calibration</button></div><p className="hint">Closing this section stops the camera. Listening and playback permissions remain separate.</p>{message&&<p role="status">{message}</p>}</section>;
}
