import React,{useMemo,useState} from 'react';
import catalog from '../shared/glossary-catalog.json';
import {glossarySchema,type Glossary} from '../shared/config';
export function GlossaryLibrary({load}:{load:(glossary:Glossary)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[direction,setDirection]=useState(''),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(0),[error,setError]=useState('');
 const categories=useMemo(()=>[...new Set(catalog.entries.map(e=>e.category))].sort(),[]);
 const results=useMemo(()=>catalog.entries.filter(e=>(!category||e.category===category)&&(!direction||e.direction===direction)&&(e.source+' '+e.target+' '+e.notes).toLocaleLowerCase().includes(query.toLocaleLowerCase())),[query,category,direction]);
 function choose(id:string){setSelected(values=>values.includes(id)?values.filter(v=>v!==id):values.length<100?[...values,id]:values);}
 function useSelection(){const entries=catalog.entries.filter(e=>selected.includes(e.id));const translations=entries.map(e=>({source:e.source,target:e.target}));const termMap=new Map<string,string>();for(const term of translations.flatMap(t=>[t.source,t.target]))if(!termMap.has(term.toLocaleLowerCase()))termMap.set(term.toLocaleLowerCase(),term);const terms=[...termMap.values()];const glossary={terms:terms.slice(0,100),translations};const parsed=glossarySchema.safeParse(glossary);if(!parsed.success){setError('Selected entries have duplicate source terms. Choose one meaning for each source before applying.');return;}load(parsed.data);setError(terms.length>100?'All selected mappings loaded. Recognition hints use the first 100 unique phrases. Review, then Apply glossary.':'Selection loaded into your editable glossary. Review, then Apply glossary.');}
 return <section className="glossary-library"><button onClick={()=>setOpen(!open)} aria-expanded={open}>Browse supplied medical & insurance preset</button>{open&&<>
  <h4>{catalog.name}</h4><p className="hint">2,192 working entries with a separate reverse index. Supplied by the owner; independently unverified. Context and alternatives remain reference notes. Select up to 100 directional mappings for this meeting; the full library stays searchable locally.</p>
  <div className="glossary-filters"><input aria-label="Search supplied glossary" placeholder="Find a term or context" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><select aria-label="Glossary category" value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Glossary direction" value={direction} onChange={e=>{setDirection(e.target.value);setPage(0);}}><option value="">Both directions</option><option value="en-bs">English → Bosnian</option><option value="bs-en">Bosnian → English</option></select></div>
  <p>{results.length} results · {selected.length}/100 selected</p><div className="glossary-results">{results.slice(page*40,page*40+40).map(entry=><div className="glossary-entry" key={entry.id}><label className="check"><input type="checkbox" aria-label={`Select ${entry.source} (${entry.direction})`} disabled={selected.length>=100&&!selected.includes(entry.id)} checked={selected.includes(entry.id)} onChange={()=>choose(entry.id)}/><span><strong>{entry.source}</strong><span className="glossary-target">{entry.target}</span></span></label><span className="glossary-direction">{entry.direction==='en-bs'?'English → Bosnian':'Bosnian → English'} · {entry.category}</span>{entry.notes&&<p>{entry.notes}</p>}{entry.alternatives&&<p>Alternatives: {entry.alternatives}</p>}</div>)}</div>
  <div className="actions"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button disabled={(page+1)*40>=results.length} onClick={()=>setPage(page+1)}>Next</button><button disabled={!selected.length} onClick={useSelection}>Load selected terms</button><button onClick={()=>setSelected([])}>Clear selection</button></div>{error&&<p role="status">{error}</p>}
 </>}</section>;
}
