import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as Dialog from '@radix-ui/react-dialog';
import {Settings,PanelTop,Play,Pause,Square,ChevronDown,X,Pin,Check,Copy,Search,ArrowDown,Download,SlidersHorizontal} from 'lucide-react';
import {BRAND,draftVisibility,descriptions,selectProfile,destination,preferencesSchema,type Preferences,type Processing,type Glossary} from '../shared/config';
import {displayed,changedAfter,type Group} from '../shared/transcript';
import type {State,Command} from '../shared/protocol';
import './style.css';
import {AccountPanel} from './account';
import {Brand} from './brand';
import {Onboarding} from './onboarding';
import type {BillingView} from '../shared/billing';
const small=new URLSearchParams(location.search).has('compact');
function App(){
 const [s,setS]=useState<State|null>(null),[error,setError]=useState(''),[sheet,setSheet]=useState(''),[query,setQuery]=useState(''),[following,setFollowing]=useState(true),[authorize,setAuthorize]=useState(false);
 const [account,setAccount]=useState<BillingView|null>(null),[settingsQuery,setSettingsQuery]=useState('');
 const last=useRef(-1),scroller=useRef<HTMLDivElement>(null);
 useEffect(()=>{const receive=(v:State)=>{if(v.sequence>=last.current){last.current=v.sequence;setS(v);}};const off=window.intera.subscribe(receive);void window.intera.snapshot().then(receive);return off;},[]);
 useEffect(()=>{let alive=true;const refresh=()=>{void window.intera.billing({type:'status'}).then(r=>{if(alive&&r.view)setAccount(r.view);}).catch(()=>{});};refresh();const timer=setInterval(refresh,30000);return()=>{alive=false;clearInterval(timer);};},[sheet,s?.status]);
 async function send(c:Command){const r=await window.intera.command(c);if(!r.ok)setError(r.message??'Could not complete action.');return r;}
 useEffect(()=>{if(s){document.documentElement.dataset.theme=s.preferences.theme;document.documentElement.dataset.platform=s.platform;}},[s?.preferences.theme]);
 useEffect(()=>{if(!small&&following&&!s?.hold&&scroller.current&&!window.getSelection()?.toString())scroller.current.scrollTop=scroller.current.scrollHeight;},[s?.transcript.event,following,s?.hold]);
 const compactTurn=(s?.hold??s?.transcript)?.groups.at(-1)?.id;
 useEffect(()=>{if(small&&scroller.current&&!s?.hold&&!window.getSelection()?.toString())scroller.current.scrollTop=0;},[compactTurn]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='f'){e.preventDefault();document.querySelector<HTMLInputElement>('#search')?.focus();}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.code==='Space'){e.preventDefault();void send({type:'hold'});}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 if(!s)return <div className="loading">Opening {BRAND}…</div>;
 const running=['connecting','listening','local-test','stopping'].includes(s.status);
 const p=s.preferences,canStart=p.funding==='personal'?s.keyStored:!!account?.summary?.managedStreamingAvailable,active=running||s.status==='paused'?(s.effective?.profile??p.processing.profile):p.processing.profile;
 const transcript=s.hold??s.transcript;
 const groups=transcript.groups.filter(g=>(displayed(g,draftVisibility(p)).source+' '+displayed(g,draftVisibility(p)).translation).toLowerCase().includes(query.toLowerCase()));
 const shown=small?groups.slice(-1):groups;
 const start=()=>{if(!canStart&&!s.demo){setSheet('Welcome');return;}if(s.status==='paused')void send({type:'start'});else setAuthorize(true);};
 return <div className={`app ${small?'compact':''}`} style={{'--source-size':`${p.sourceSize}px`,'--translation-size':`${p.translationSize}px`,'--source-spacing':p.sourceSpacing,'--translation-spacing':p.translationSpacing} as React.CSSProperties}>
  {s.demo&&<div className="demo-banner">Demo — simulated conversation · no audio captured or sent</div>}
  <div className="toolbar"><Brand label={!small}/>
   <div className="capture-info"><span className={`status-dot ${s.status==='listening'?'on':''}`}/><div><strong>{s.status==='local-test'?'Local audio test':s.status==='listening'?'Listening':s.status==='connecting'?'Connecting':s.status==='paused'?'Paused':s.status==='error'?'Needs attention':'Ready'}</strong><span>Computer audio · all playback</span></div></div>
   {!small&&<div className="language"><span>{({two_way:'English ↔ Bosanski',bs:'English → Bosanski',en:'Bosanski → English',none:'Transcription only'})[(s.effective??p.processing).mode]}</span></div>}
   <button className="profile-button" onClick={()=>setSheet('Performance')} aria-label="Performance profile"><SlidersHorizontal size={15}/>{active}<ChevronDown size={14}/></button>
   <div className="toolbar-actions">{running?<><button onClick={()=>void send({type:'pause'})} disabled={s.status==='stopping'} title="Pause listening"><Pause size={16}/>{!small&&'Pause'}</button><button onClick={()=>void send({type:'stop'})} aria-label="Stop listening"><Square size={15}/></button></>:<button className="primary" onClick={start}><Play size={15}/>{s.status==='paused'?'Resume':'Start'}</button>}
   {!small&&<button className="icon" title="Open compact view" aria-label="Open compact view" onClick={()=>void send({type:'compact'})}><PanelTop size={19}/></button>}
   <button className="icon" title="Settings" aria-label="Settings" onClick={()=>setSheet('Reading')}><Settings size={19}/></button></div>
  </div>
  {s.pending&&<div className="notice">Pending: {s.pending.config.profile} · {s.pending.timing==='pause'?'applies on Resume':'next session'} <button onClick={()=>void send({type:'cancel-pending'})}>Cancel pending</button></div>}
  {s.managed&&s.status!=='error'&&s.managed.boundaryReached&&<div className="notice" role="status">Funded session limit reached. Listening is paused; your meeting and text are unchanged. Usage is finalizing.</div>}
  {s.managed&&!s.managed.finalizing&&running&&s.managed.reservedMs-s.managed.provisionalMs<=120000&&<div className="notice" role="status">This funded session has about {Math.max(0,Math.ceil((s.managed.reservedMs-s.managed.provisionalMs)/60000))} minutes left. Listening will pause at its limit.</div>}
  {s.status==='error'&&<div className="notice error" role="alert">{s.message}</div>}
  {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={14}/></button></div>}
  {!small&&<div className="reading-bar"><span>CONVERSATION <span className="count">{groups.length}</span></span><label className="search"><Search size={15}/><input id="search" aria-label="Search conversation" placeholder="Find in conversation" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={s.hold?'selected':''} onClick={()=>void send({type:'hold'})}>{s.hold?`Release reading · ${s.transcript.event-s.hold.event} updates`:'Hold reading'}</button><button title="Export transcript" aria-label="Export transcript" disabled={!groups.length} onClick={()=>void send({type:'export',format:'txt'})}><Download size={16}/></button></div>}
  <main aria-label="Chronological transcript" ref={scroller} className="conversation" onScroll={()=>{const el=scroller.current;if(el&&!small&&el.scrollHeight-el.scrollTop-el.clientHeight>=70)setFollowing(false);}}>
   {!shown.length&&!query?<div className="empty"><div className="empty-icon"><Brand label={false}/></div><p className="eyebrow">YOUR INTERPRETATION, SUPPORTED</p><h1>Ready to interpret</h1><p>Read the original. Follow the translation.<br/>Keep your attention on the conversation.</p><div className="readiness"><span><span className={`status-dot ${canStart?'on':''}`}/>{p.funding==='personal'?'Personal key mode':canStart?'Managed listening ready':'Sign in for managed listening'}</span><span>English ↔ Bosanski</span><span>{p.processing.profile} · {p.drafts?'Live drafts':'Settled text'}</span></div><button className="primary large" onClick={()=>canStart?start():setSheet('Welcome')}><Play size={17}/>{canStart?'Start listening':'Set up Intera'}</button><button className="text-button" onClick={()=>void send({type:'demo'})}>Explore a clearly labeled demo</button><p className="scope">Listens to a copy of all computer playback, including notifications.<br/>Your meeting microphone is not requested.</p></div>:shown.map(g=><Turn key={g.id} g={g} s={s} send={send} />)}
   {!!query&&!shown.length&&<p className="no-results">No matching text.</p>}
  </main>
  {!following&&!small&&<button className="jump" onClick={()=>{setFollowing(true);scroller.current?.scrollTo({top:scroller.current.scrollHeight});}}><ArrowDown size={15}/>Jump to live</button>}
  <footer><div className="meter" aria-label={`Audio level ${Math.round(s.meter*100)} percent`}><i style={{width:`${Math.min(100,s.meter*400)}%`}}/></div><span>{s.captureHealth}</span>{p.funding==='managed'&&<button className="text-button" onClick={()=>setSheet('Account')}>{s.managed&&!s.managed.finalizing&&running?`${Math.ceil(s.managed.provisionalMs/60000)} min sent · estimate`:account?.summary?.usage?.finalizing?'Usage finalizing':account?.summary?`${Math.floor(account.summary.remainingMs/60000)} min available`:'Account'}</button>}<span className="footer-right">{small?<button onClick={()=>void send({type:'hold'})}>{s.hold?'Release reading':'Hold reading'}</button>:<>{p.drafts?'Live drafts':'Settled text'}<span>·</span>{s.networkHealth}<span>·</span><button className="text-button" onClick={()=>setSheet('Session')}>Session actions</button></>}</span></footer>
  <Dialog.Root open={!!sheet} onOpenChange={open=>{if(!open)setSheet('');}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="sheet"><div className="sheet-heading"><Dialog.Title>{sheet==='Performance'?'Speed & finalization':'Settings'}</Dialog.Title><Dialog.Close className="icon" aria-label="Close settings"><X size={20}/></Dialog.Close></div><Dialog.Description className="sheet-description">Your preferences. Your pace. Changes show what is active.</Dialog.Description><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections"><input aria-label="Search settings" placeholder="Find a setting" value={settingsQuery} onChange={e=>setSettingsQuery(e.target.value)}/><div className="tabs">{['Performance','Connection','Audio','Languages','Reading','Session','Account','Welcome'].filter(t=>(t+' '+({Performance:'speed endpoint custom profile',Connection:'key personal managed region import export',Audio:'playback test headset',Languages:'translation glossary terminology',Reading:'font size theme drafts',Session:'clear export hold',Account:'billing payment sign in subscription',Welcome:'onboarding setup'}[t]??'')).toLowerCase().includes(settingsQuery.toLowerCase())).map(t=><button key={t} className={sheet===t?'selected':''} onClick={()=>setSheet(t)}>{t==='Welcome'?'Setup guide':t}</button>)}</div></nav>{sheet==='Welcome'?<Onboarding s={s} send={send} done={()=>setSheet('')}/>:sheet==="Account"?<AccountPanel/>:<SettingsBody section={sheet} s={s} send={send}/>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
  <Dialog.Root open={authorize} onOpenChange={setAuthorize}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="confirm"><Dialog.Title>Start listening to computer audio?</Dialog.Title><Dialog.Description>All playback, including other apps and notifications, will be sent to Soniox for transcription and translation. Confirm that you are authorized to share this audio. {p.funding==='managed'?'Verified audio duration, including silence, uses your allowance. No automatic overage charges.':'Soniox may charge your personal provider account.'}</Dialog.Description><p className="destination">{destination(p.funding==='managed'?(account?.summary?.usage?.region??p.region):p.region)}</p><p>{p.processing.profile} · {p.drafts?'Live drafts':'Settled text'} · English ↔ Bosnian</p><p>No physical microphone is requested. Display permission may be required to acquire audio; video frames are never used.</p><div className="actions"><Dialog.Close>Cancel</Dialog.Close><button className="primary" disabled={!canStart} onClick={()=>{setAuthorize(false);void send({type:'start'});}}>Start listening</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
function Turn({g,s,send}:{g:Group;s:State;send:(c:Command)=>Promise<unknown>}){
 const [editing,setEditing]=useState(false),[source,setSource]=useState(''),[translation,setTranslation]=useState(''),[rename,setRename]=useState(false),[name,setName]=useState('');
 const d=g.pinned??displayed(g,draftVisibility(s.preferences)),changed=changedAfter(g),draft=!!(g.sourceDraft||g.translationDraft),speaker=s.names[`${g.epoch}:${g.speaker}`]??(g.speaker==='Unknown'?'Unknown':`Speaker ${g.speaker}`);
 return <article className={`turn ${g.pinned?'pinned':''}`}><div className="turn-meta"><button className="speaker" onClick={()=>{setName(speaker);setRename(!rename);}}>{speaker}</button><span>{g.language==='en'?'English → Bosnian':g.language==='bs'?'Bosanski → English':`${g.language} · transcription / unpaired`}</span><span>Connection {g.epoch}</span><span className="settlement">{g.edit?'Human edited':draft?'Live draft':g.translation?'Provider-finalized text':'Pending translation'}</span></div>
  {rename&&<form className="rename" onSubmit={e=>{e.preventDefault();void send({type:'rename',id:`${g.epoch}:${g.speaker}`,name});setRename(false);}}><input aria-label="Speaker name" value={name} onChange={e=>setName(e.target.value)} maxLength={60}/><button>Save name</button></form>}
  {editing?<div className="edit-grid"><label>Original<textarea value={source} onChange={e=>setSource(e.target.value)}/></label><label>Translation<textarea value={translation} onChange={e=>setTranslation(e.target.value)}/></label><p>Source edits can make the machine translation outdated. Provider originals are retained.</p><div className="actions"><button onClick={()=>setEditing(false)}>Cancel</button><button className="primary" onClick={()=>{void send({type:'group',id:g.id,action:'edit',edit:{source,translation}});setEditing(false);}}>Save edits</button></div></div>:<div className={`paired ${!s.preferences.showSource?'translation-only':''}`}>
   {s.preferences.showSource&&<div className="source"><div className="column-label">ORIGINAL</div><p>{d.source||'Waiting for source…'}</p></div>}<div className="translation"><div className="column-label">TRANSLATION {g.unpaired&&'· ALIGNMENT UNCONFIRMED'}</div><p>{d.translation||<span className="pending-text">{s.preferences.processing.mode==='none'?'Transcription only':'Waiting for translation…'}</span>}</p></div></div>}
  {changed&&<details className="changed"><summary>Changed after interpretation</summary><p>Previously delivered: {g.interpreted?.source}</p><p>{g.interpreted?.translation}</p></details>}
  {g.edit&&<details><summary>Provider original · translation may be outdated</summary><p>{g.source}</p><p>{g.translation}</p></details>}
  <div className="turn-actions"><button className={g.pinned?'selected':''} onClick={()=>void send({type:'group',id:g.id,action:'pin'})}><Pin size={14}/>{g.pinned?'Unpin snapshot':'Pin'}</button><button className={g.interpreted?'selected':''} onClick={()=>void send({type:'group',id:g.id,action:'interpreted'})}><Check size={14}/>{g.interpreted?'Interpreted':'Mark interpreted'}</button><button onClick={()=>void navigator.clipboard.writeText(`${d.source}\n${d.translation}`)}><Copy size={14}/>Copy pair</button><button onClick={()=>{setSource(d.source);setTranslation(d.translation);setEditing(true);}}>Edit</button></div>
 </article>;
}
function SettingsBody({section,s,send}:{section:string;s:State;send:(c:Command)=>Promise<any>}){
 const [draft,setDraft]=useState(s.preferences),[key,setKey]=useState(''),[persist,setPersist]=useState(true),[timing,setTiming]=useState<'now'|'pause'|'next'>('pause'),[presetName,setPresetName]=useState(''),[terms,setTerms]=useState(''),[mappings,setMappings]=useState(''),[saveGlossary,setSaveGlossary]=useState(false),[feedback,setFeedback]=useState(''),[imported,setImported]=useState<Preferences|null>(null);
 useEffect(()=>setDraft(s.preferences),[JSON.stringify(s.preferences)]);
 const p=draft.processing;
 function process(next:Processing){setDraft({...draft,processing:next});}
 async function apply(next=draft){const parsed=preferencesSchema.safeParse(next);if(!parsed.success){setFeedback('Invalid setting. Check the allowed ranges.');return;}const r=await send({type:'preferences',preferences:parsed.data,timing});if(r.ok)setFeedback('Preferences saved. Active and pending states are shown separately.');}
 function cosmetic(change:Partial<Preferences>){void apply({...s.preferences,...change});}
 return <div className="settings-body">{section==='Performance'&&<>
  <div className="active-line"><span>Active now <strong>{['listening','connecting','stopping'].includes(s.status)?s.effective?.profile:'No active request'}</strong></span><span>Saved <strong>{s.preferences.processing.profile}</strong></span></div>
  <div className="profile-options">{(['Speed','Balanced','Accuracy-first','Custom'] as const).map(name=><button key={name} className={p.profile===name?'selected':''} onClick={()=>process(selectProfile(p,name))}>{name}</button>)}</div><p className="explanation">{descriptions[p.profile]}</p>
  <div className="config-preview"><span>Endpoint detection <b>{p.endpoint.enabled?'On':'Off'}</b></span>{p.endpoint.enabled&&<><span>Maximum delay <b>{p.endpoint.delay} ms</b></span><span>Earlier-finalization level <b>{p.endpoint.level}</b></span><span>Sensitivity <b>{p.endpoint.sensitivity.toFixed(1)}</b></span></>}</div>
  <p className="hint">The maximum delay is a bound after speech ends, not a minimum wait or translation SLA. All profiles use the same model and audio quality. Accuracy is not evaluated.</p>
  <label className="check"><input type="checkbox" checked={s.preferences.drafts} onChange={e=>cosmetic({drafts:e.target.checked})}/>Show live drafts as the provider returns them</label><p className="hint">Independent of the processing profile. Settled text is finalized by the provider, not clinically verified.</p>
  <details open={p.profile==='Custom'}><summary>Custom processing controls</summary><label className="check"><input type="checkbox" checked={!p.endpoint.enabled} onChange={e=>process({...p,profile:'Custom',endpoint:{...p.endpoint,enabled:!e.target.checked}})}/>Natural finalization (endpoint detection off)</label><p className="hint">Text still streams incrementally. Stable output may arrive later, with fewer explicit boundaries.</p><div className="fields">{(['delay','level','sensitivity'] as const).map(field=><label key={field}>{field==='delay'?'Maximum delay (500–3000 ms)':field==='level'?'Earlier finalization (0–3)':'Sensitivity (-1 to 1)'}<input type="number" disabled={!p.endpoint.enabled} min={field==='delay'?500:field==='level'?0:-1} max={field==='delay'?3000:field==='level'?3:1} step={field==='sensitivity'?0.1:field==='delay'?100:1} value={p.endpoint[field]} onChange={e=>process({...p,profile:'Custom',endpoint:{...p.endpoint,[field]:e.target.valueAsNumber}})}/></label>)}</div>{p.endpoint.sensitivity<0&&p.endpoint.level>0&&<p className="warning">These settings pull in opposite directions: fewer endpoints, but earlier finalization when they occur.</p>}<button onClick={()=>process({...p,profile:'Custom',endpoint:{enabled:false,delay:2000,level:0,sensitivity:0}})}>Provider defaults</button><p className="hint">Provider endpoint detection defaults to off. When enabled: 2000 ms, level 0, sensitivity 0.</p></details>
  <div className="preset-row"><input placeholder="Named preset" aria-label="Named preset" maxLength={40} value={presetName} onChange={e=>setPresetName(e.target.value)}/><button disabled={!presetName.trim()} onClick={()=>{void apply({...draft,presets:[...draft.presets.filter(v=>v.name!==presetName.trim()),{name:presetName.trim(),endpoint:p.endpoint}]});setPresetName('');}}>Save preset</button></div>{draft.presets.map(v=><div className="preset-row" key={v.name}><button onClick={()=>process({...p,profile:'Custom',endpoint:v.endpoint})}>{v.name}</button><button onClick={()=>void apply({...draft,presets:draft.presets.filter(x=>x.name!==v.name)})}>Delete</button></div>)}
  <button onClick={()=>process(selectProfile(p,'Balanced'))}>Restore app defaults</button>
 </>}
 {section==='Connection'&&<><h3>Listening service</h3><label>Funding mode<select value={draft.funding} disabled={s.status==='listening'||s.status==='connecting'} onChange={e=>setDraft({...draft,funding:e.target.value as Preferences['funding']})}><option value="managed">Managed · Intera allowance</option><option value="personal">Personal Soniox key · billed separately</option></select></label>{draft.funding==='managed'?<p>Sign in from Account. Intera supplies a short-lived credential in its trusted desktop process. Your personal key is not used and company credentials are never shown here.</p>:<><p>Use a personal project key with real-time transcription and translation access.</p><label>Processing region<select value={draft.region} disabled={['listening','connecting','stopping','local-test'].includes(s.status)} onChange={e=>setDraft({...draft,region:e.target.value as Preferences['region']})}><option value="us">United States</option><option value="eu">European Union</option><option value="jp">Japan</option><option value="in">India</option></select></label><p className="destination">{destination(draft.region)}</p><p className="hint">Regional deployments require the matching regional project key and enabled account access. No automatic failover.</p><label>Soniox API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={s.keyStored?'Key already added — enter to replace':'Paste your personal key'}/></label><label className="check"><input type="checkbox" checked={persist} disabled={!s.secureStorage} onChange={e=>setPersist(e.target.checked)}/>Protect with OS secure storage {s.secureStorage?'':'(unavailable; session only)'}</label><div className="actions"><button disabled={!key.trim()} onClick={async()=>{const value=key;setKey('');const r=await send({type:'key',key:value,persist:persist&&s.secureStorage});if(r.ok)setFeedback('Key added. Next: Audio → local playback test.');}}>Save key</button><button onClick={()=>void send({type:'validate-key'})}>Validate without audio</button><button onClick={()=>void send({type:'forget-key'})}>Forget key</button></div><p className="hint">No cloud transcript history, analytics, or local conversation files are created by Intera. Export is explicit. Provider processing is subject to your account terms.</p></>}<button onClick={()=>void send({type:'export-settings'})}>Export preferences</button><button onClick={async()=>{const r=await send({type:'import-settings'});if(r.preview)setImported(r.preview);}}>Import preferences…</button>{imported&&<div className="import-preview"><h4>Review imported changes</h4><pre>{JSON.stringify(imported,null,2)}</pre><button onClick={()=>{setDraft(imported);setImported(null);setFeedback('Preview loaded. Save below to apply.');}}>Use this preview</button><button onClick={()=>setImported(null)}>Cancel</button></div>}</>}
 {section==='Audio'&&<><h3>Computer audio — all playback</h3><p>Includes remote participants, other audible apps and notifications, even through headphones. No physical microphone is requested.</p><p className="hint">macOS 14.2+ uses the runtime’s Core Audio tap path. A display stream may require screen permission. Its video frames are never displayed, stored or uploaded. A development terminal may own the permission.</p><div className="actions"><button onClick={()=>void send({type:'local-test'})}>Start local playback test</button><button onClick={()=>void send({type:'stop'})}>Stop test</button></div><div className="config-preview"><span>Sample delivery <b>{s.captureHealth}</b></span><span>Packets <b>{s.packets}</b></span><span>Actual format <b>{s.audio?`${s.audio.sampleRate} Hz · ${s.audio.channels} ch · PCM16`:'Not acquired'}</b></span></div><p className="hint">Play an authorized sound while testing. Silent samples show delivery, not proof of audible capture. The local test never opens a provider connection.</p><label>Audio packet duration<select value={p.packetMs} onChange={e=>process({...p,packetMs:Number(e.target.value) as 40|80|120})}><option value="40">40 ms</option><option value="80">80 ms (default)</option><option value="120">120 ms</option></select></label><p className="hint">Independent transport setting, identical across standard profiles. Selected inputs and replay are not available in this build.</p></>}
 {section==='Languages'&&<><h3>Language direction</h3><label>Translation<select value={p.mode} onChange={e=>process({...p,mode:e.target.value as Processing['mode']})}><option value="two_way">Automatic · English ↔ Bosnian</option><option value="bs">Translate to Bosnian</option><option value="en">Translate to English</option><option value="none">Transcription only</option></select></label><label className="check"><input type="checkbox" checked={p.strict} onChange={e=>process({...p,strict:e.target.checked})}/>Restrict recognition to English and Bosnian</label><label className="check"><input type="checkbox" checked={p.speakers} onChange={e=>process({...p,speakers:e.target.checked})}/>Speaker labels</label><p className="hint">Language does not identify a doctor or patient. Speaker identities reset on every connection. Bosnian Latin/ijekavian and medical-domain context are hints, not guarantees.</p><h3>Session terminology</h3><p className="hint">Enter only necessary terms, without patient identifiers. Saving replaces the current glossary; change while stopped.</p><label>Recognition terms (one per line)<textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label><label>Directional translation mappings (source = target)<textarea value={mappings} onChange={e=>setMappings(e.target.value)}/></label><label className="check"><input type="checkbox" checked={saveGlossary} onChange={e=>setSaveGlossary(e.target.checked)}/>Save as a generic glossary for later sessions</label><button onClick={()=>{const glossary:Glossary={terms:terms.split('\n').map(t=>t.trim()).filter(Boolean),translations:mappings.split('\n').filter(t=>t.trim()).map(t=>{const [source,...target]=t.split('=');return {source:source.trim(),target:target.join('=').trim()};})};void send({type:'glossary',glossary,save:saveGlossary});}}>Apply glossary</button></>}
 {section==='Reading'&&<><h3>Make room for reading</h3><label className="check"><input type="checkbox" checked={s.preferences.drafts} onChange={e=>cosmetic({drafts:e.target.checked})}/>Show live drafts</label><label className="check"><input type="checkbox" checked={s.preferences.showSource} onChange={e=>cosmetic({showSource:e.target.checked})}/>Show original text</label><label>Original size · {s.preferences.sourceSize}px<input type="range" min="14" max="24" value={s.preferences.sourceSize} onChange={e=>cosmetic({sourceSize:Number(e.target.value)})}/></label><label>Translation size · {s.preferences.translationSize}px<input type="range" min="18" max="36" value={s.preferences.translationSize} onChange={e=>cosmetic({translationSize:Number(e.target.value)})}/></label><div className="fields">{(['source','translation'] as const).map(kind=><label key={kind}>{kind==='source'?'Original':'Translation'} line spacing<input aria-label={`${kind} line spacing`} type="range" min="1.2" max="2" step="0.05" value={s.preferences[kind==='source'?'sourceSpacing':'translationSpacing']} onChange={e=>cosmetic({[kind==='source'?'sourceSpacing':'translationSpacing']:Number(e.target.value)})}/></label>)}</div><label className="check"><input type="checkbox" disabled={!s.preferences.drafts} checked={s.preferences.sourceDrafts} onChange={e=>cosmetic({sourceDrafts:e.target.checked})}/>Show original drafts</label><label className="check"><input type="checkbox" disabled={!s.preferences.drafts} checked={s.preferences.translationDrafts} onChange={e=>cosmetic({translationDrafts:e.target.checked})}/>Show translation drafts</label><label>Appearance<select value={s.preferences.theme} onChange={e=>cosmetic({theme:e.target.value as Preferences['theme']})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><p className="hint">Reading preferences apply immediately to both windows, without restarting capture. Reduced motion and high contrast follow your system preferences.</p><p>Find: {s.platform==='darwin'?'⌘':'Ctrl'} F<br/>Hold reading: {s.platform==='darwin'?'⌘':'Ctrl'} Shift Space</p></>}
 {section==='Session'&&<><h3>Session controls</h3><p>{s.message}</p><div className="session-actions"><button onClick={()=>void send({type:'finish'})}>Finish this turn</button><button onClick={()=>void send({type:'hold'})}>{s.hold?'Release reading':'Hold reading'}</button><button onClick={()=>void send({type:'export',format:'txt'})}>Export text…</button><button onClick={()=>void send({type:'export',format:'json'})}>Export revisions as JSON…</button><button onClick={()=>void send({type:'clear'})}>Stop and clear session</button><button onClick={()=>void send({type:'demo'})}>Start simulated demo</button></div><p className="hint">Finish this turn explicitly asks the provider to finalize already-sent audio. It can affect segmentation and speaker labeling. Hold reading freezes the view while listening continues.</p><p className="hint">Clear erases in-memory text. It does not delete exported copies or prove provider deletion.</p></>}
 {['Performance','Languages','Audio','Connection'].includes(section)&&<div className="apply-area">{['listening','connecting','paused'].includes(s.status)&&<><label>Apply processing changes<select value={timing} onChange={e=>setTiming(e.target.value as typeof timing)}><option value="pause">When I pause · on Resume</option><option value="next">Next session</option><option value="now">Apply now · reconnect</option></select></label>{timing==='now'&&<p className="warning">Reconnecting creates a brief capture gap. Speech during that gap will not be uploaded. Speaker IDs start a new epoch.</p>}</>}<button className="primary" onClick={()=>void apply()}>Save preferences</button></div>}{feedback&&<p className="feedback" role="status">{feedback}</p>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);

import './premium.css';

