import React,{useState} from 'react';
import type {Command,State} from '../shared/protocol';
export function Meetings({s,send}:{s:State;send:(command:Command)=>Promise<{ok:boolean;message?:string}>}){
 const [title,setTitle]=useState(''),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(false);
 async function action(command:Command){setWorking(true);try{const result=await send(command);setMessage(result.ok?command.type==='save-meeting'?'Meeting saved on this device.':command.type==='new-meeting'?'New meeting ready. Click Start when authorized.':'Meeting library updated.':result.message??'Could not complete action.');}finally{setWorking(false);}}
 return <section className="meeting-library"><h3>Your meetings</h3><p>Save text and corrections on this device, protected by its secure storage. No recordings are saved. Nothing is sent to Intera AI or billing. Save only conversations you are authorized to retain.</p>{s.meetingStorageError&&<p role="status">{s.meetingStorageError}</p>}
 <label>Meeting title<input value={title} maxLength={120} placeholder="Use a generic title" onChange={e=>setTitle(e.target.value)}/></label><div className="actions"><button disabled={working||!s.transcript.groups.length||!s.secureStorage} onClick={()=>void action({type:'save-meeting',title:title.trim()||`Meeting ${new Date().toLocaleString()}`})}>Stop & save meeting</button><button disabled={working} onClick={async()=>{if(s.transcript.groups.length&&!s.savedMeeting&&!confirm('Start a new meeting without saving this text?'))return;await action({type:'new-meeting'});}}>New meeting</button></div><p className="hint">Saving stops listening first. New meeting clears the reader without starting capture. Saved meetings open for review; start a new meeting to listen again.</p>
 <label>Find a saved meeting<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles"/></label><div className="meeting-list">{(s.meetings??[]).filter(m=>m.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(meeting=><article key={meeting.id}><div><strong>{meeting.title}</strong><p>{new Date(meeting.savedAt).toLocaleString()} · {meeting.turns} turns{meeting.demo?' · Simulated demo':''}</p></div><div className="actions"><button disabled={working} onClick={async()=>{if(s.transcript.groups.length&&!s.savedMeeting&&!confirm('Replace the unsaved reader with this saved meeting?'))return;await action({type:'open-meeting',id:meeting.id});}}>Open</button><button disabled={working} onClick={async()=>{if(confirm('Delete this saved meeting from this device? Exported copies are unaffected.'))await action({type:'delete-meeting',id:meeting.id});}}>Delete</button></div></article>)}</div>{!s.meetings?.length&&<p>No saved meetings yet.</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
