import React,{useState} from 'react';
import {AccountPanel} from './account';
import {selectProfile} from '../shared/config';
import type {State,Command} from '../shared/protocol';
import {DirectSoniox} from './direct-soniox';
export function Onboarding({s,send,done}:{s:State;send:(c:Command)=>Promise<{ok:boolean;message?:string}>;done:()=>void}){
 const [step,setStep]=useState(0),[path,setPath]=useState<'direct'|'managed'>('direct');
 return <div className="onboarding"><h2>Set up Intera AI</h2><ol className="setup-steps">{['How you pay','Meeting playback','Your reading pace','Ready'].map((name,i)=><li key={name}><button aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {name}</button></li>)}</ol>
 {step===0&&<><div className="actions" aria-label="Payment setup choices"><button aria-pressed={path==='direct'} onClick={()=>setPath('direct')}>Pay Soniox directly</button><button aria-pressed={path==='managed'} onClick={()=>setPath('managed')}>Use an Intera AI plan</button></div>{path==='direct'?<DirectSoniox s={s} send={send} onNext={()=>setStep(1)}/>:<><AccountPanel/><p>Eligible new accounts receive 30 minutes, expiring after 14 days. Managed listening depends on service readiness.</p><button disabled={['listening','connecting','stopping','local-test'].includes(s.status)} onClick={()=>void send({type:'preferences',preferences:{...s.preferences,funding:'managed'},timing:'next'})}>Select Intera AI allowance mode</button></>}</>}
 {step===1&&<><h3>Listen to meeting playback</h3><p>Choose your meeting’s speaker or headset in the meeting app. Intera AI copies all computer playback, including notifications. It does not request your physical microphone.</p><p>Play an authorized sample, then run this local test. Nothing is uploaded.</p><div className="actions"><button onClick={()=>void send({type:'local-test'})}>Start local playback test</button><button onClick={()=>void send({type:'stop'})}>Stop test</button></div><p role="status">{s.captureHealth} · {s.audio?`${s.audio.sampleRate} Hz / ${s.audio.channels} channels`:'No samples yet'}</p></>}
 {step===2&&<><h3>English ↔ Bosanski</h3><p>Choose responsiveness. All plans retain the same model and audio fidelity.</p><div className="profile-options">{(['Speed','Balanced','Accuracy-first'] as const).map(profile=><button key={profile} className={s.preferences.processing.profile===profile?'selected':''} onClick={()=>void send({type:'preferences',preferences:{...s.preferences,processing:selectProfile(s.preferences.processing,profile)},timing:'next'})}>{profile}</button>)}</div><div className="text-preview"><small>SYNTHETIC TEXT PREVIEW</small><p>Could you repeat the last sentence?</p><strong>Možete li ponoviti posljednju rečenicu?</strong></div></>}
 {step===3&&<><h3>Your workspace is ready to review</h3>{s.preferences.funding==='personal'?<><p>{s.keyStored?'Your Soniox key is connected.':'Connect your Soniox key in How you pay before live listening.'} Start sends audio directly to your Soniox project after your authorization.</p><p>Soniox bills your API use directly. Intera AI adds no usage fee and does not deduct subscription hours. A connected key does not verify your balance; review funding and budgets in Soniox.</p></>:<><p>Start checks your signed-in account and reserves eligible time. Audio is sent directly to Soniox after your authorization. Usage is finalized from provider records after stopping.</p><p>Managed beta access depends on the configured service and account eligibility.</p></>}<p>Your existing text remains readable and exportable after Stop.</p></>}
 <div className="setup-actions"><button onClick={()=>{void send({type:'demo'});done();}}>Explore a clearly labeled demo</button>{step<3?<button className="primary" onClick={()=>{if(step===1)void send({type:'stop'});setStep(step+1);}}>Continue</button>:<button className="primary" onClick={()=>{void send({type:'preferences',preferences:{...s.preferences,onboarded:true},timing:'next'});done();}}>Open workspace</button>}</div></div>;
}
